name: peviitor.ro
on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  jmeter_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download and install JMeter
      run: |
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz
        cd apache-jmeter-5.6.3/lib
        wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2.1/cmdrunner-2.2.1.jar
        cd ext/
        wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.6/jmeter-plugins-manager-1.6.jar
        cd ..
        java  -jar cmdrunner-2.2.1.jar --tool org.jmeterplugins.repository.PluginManagerCMD install jpgc-dummy
        export PATH=$PATH:$PWD/apache-jmeter-5.6.3/bin

    - name: Run JMeter tests
      env:
          APIKEY: ${{ secrets.APIKEY }}
          
      run: |
        cd sites 

        JMX_FILES=$(find . -name "*.jmx")

        for FILE in $JMX_FILES; do
          echo "Running test $FILE"
          $GITHUB_WORKSPACE/apache-jmeter-5.6.3/bin/./jmeter.sh -n -t $FILE -Japikey=${APIKEY}
        done
